### ISSUE TITLE
Newbie using to install this plugin

### ISSUE THREAD

**Issue by wouterschiedam** [Jezda1337/nvim-html-css#12]
Hi, im quite new to the whole vim experience I came across your plugin and it looks awesome however im having some trouble trying to install it correctly I keep getting the following error:

Error while calling lua chunk: ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this
message: .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:405: Failed to spawn process: {
  _additional_on_exit_callbacks = {},
  _shutdown_check = <userdata 1>,
  _stderr_results = {},
  _stdout_results = {},
  _user_on_exit = <function 1>,
  args = { "-sSL", "-D", "/tmp/plenary_curl_f8ef4cfe.headers", "--compressed", "-X", "GET", "http://en.wikipedia.org/wiki/Michael_Col
lins_(astronaut)" },
  command = "curl",
  enable_handlers = true,
  enable_recording = true,
  interactive = true,
  pid = "EMFILE: too many open files",
  stderr = <userdata 2>,
  stdin = <userdata 3>,
  stdout = <userdata 4>,
  user_data = {},
  <metatable> = <1>{
    __index = <table 1>,
    _create_uv_options = <function 2>,
    _execute = <function 3>,
    _pipes_are_closed = <function 4>,
    _prepare_pipes = <function 5>,
    _reset = <function 6>,
    _shutdown = <function 7>,
    _stop = <function 8>,
    add_on_exit_callback = <function 9>,
    after = <function 10>,
    after_failure = <function 11>,
    after_success = <function 12>,
    and_then = <function 13>,
    and_then_on_failure = <function 14>,
    and_then_on_failure_wrap = <function 15>,
    and_then_on_success = <function 16>,
    and_then_on_success_wrap = <function 17>,
    and_then_wrap = <function 18>,
    chain = <function 19>,
    chain_status = <function 20>,
    co_wait = <function 21>,
    is_job = <function 22>,
    join = <function 23>,
    new = <function 24>,
    pid = <function 25>,
    result = <function 26>,
    send = <function 27>,
    shutdown = <function 28>,
    start = <function 29>,
    stderr_result = <function 30>,
    sync = <function 31>,
    wait = <function 32>
  }
}
stack traceback:
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:405: in function '_execute'
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:448: in function 'start'
        ...site/pack/packer/start/plenary.nvim/lua/plenary/curl.lua:288: in function 'get'
        .../pack/packer/start/nvim-html-css/lua/html-css/remote.lua:24: in function 'get_remote_styles'
        .../pack/packer/start/nvim-html-css/lua/html-css/remote.lua:41: in function 'init'
        ...te/pack/packer/start/nvim-html-css/lua/html-css/init.lua:66: in function <...te/pack/packer/start/nvim-html-css/lua/html-c
ss/init.lua:65>
stack traceback:
        [C]: in function 'error'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:45: in function 'step'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:48: in function 'execute'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:108: in function 'run'
        ...te/pack/packer/start/nvim-html-css/lua/html-css/init.lua:65: in function <...te/pack/packer/start/nvim-html-css/lua/html-c
ss/init.lua:36>
        [C]: in function 'require'
        /Users/wouter/.config/nvim/after/plugin/cmp.lua:31: in main chunk

this is my cmp.lua : 
local cmp_status, cmp = pcall(require, "cmp")     ■ Unused local `cmp_status`.
   29 cmp.setup({
   28         sources = cmp.config.sources {
   27                         {
   26                             name = "html-css",
   25                             option = {
   24                                 max_count = {}, -- not ready yet
   23                                 enable_on = {
   22                                     "html",
   21                                     "php"
   20                                 }, -- set the file types you want the plugin to work on
   19                                 file_extensions = { "css", "sass", "less" },
   18                                 style_sheets = {
   17                                     -- example of remote styles, only css no js for now
   16                                     "https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css",
   15                                 },
   14                             },
   13                             },
   12
   11         },
   10          -- enable filename path for css config
    9         formatting = {
    8                 format = function(entry, vim_item)
    7                     if entry.source.name == "html-css" then
    6                         vim_item.menu = entry.source.menu
    5                     end
    4                     return vim_item
    3                 end
    2         }
    1 })
  31  require("html-css"):setup();

and this is what I have in my packer.lua :

use("Jezda1337/nvim-html-css")

**Comment by Jezda1337** [comment]
I didn't test on Packer but, can you try this? and do you have installed dependencies?
  use {
    "Jezda1337/nvim-html-css"
    requires = {"nvim-treesitter/nvim-treesitter", "nvim-lua/plenary.nvim"},
    config = function() require("html-css"):setup() end,
  }

**Comment by wouterschiedam** [comment]
Thanks for the quick response! The error seems to go away with this ^ . However when I try it in a html file it doesn't work. 
I have installed the dependencies aswel "nvim-lua/plenary.vim" and "nvim-treesitter/nvim-treesitter"

**Comment by Jezda1337** [comment]
You need to install this as well: [fd](https://github.com/sharkdp/fd)

**Comment by wouterschiedam** [comment]
I've read in another issue about this I installed it already with brew install fd.

**Comment by Jezda1337** [comment]
Can you share CmpStatus log?

**Comment by wouterschiedam** [comment]
when I run :CmpStatus I get this:

# ready source names
- buffer
- path
- luasnip

# unavailable source names
- nvim_lsp:lua_ls

# unused source names
- calc
- emoji
- look
- nvim_lua
- ultisnips
- spell
- TabNine

**Comment by Jezda1337** [comment]
Do you have .git/ folder or pacakge.json file inside ur root project? this two trigger plugin to be active in current work directory

**Comment by wouterschiedam** [comment]
yes I have a .git/ folder in the root of my documents this is also where I open nvim

**Comment by Jezda1337** [comment]
Okay, later today I will test with packer and will try to reproduce your problem

**Comment by wouterschiedam** [comment]
Awesome thanks for the help! I'm new to vim so it is all quite new to me

**Comment by Jezda1337** [comment]
Hey @wouterschiedam here is my packer example which works: https://gist.github.com/Jezda1337/d74c22070e523a59885ba4d3c71af2dd

**Comment by wouterschiedam** [comment]
Thanks for taking ur time to help me out! I think I got a step closer to getting it to work however now I have this error:

Error while calling lua chunk: .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:499: 'fd -a -e html --exclude node_modules' was unable to complete in 5000 ms

in main chunk cmp.lua line 82:
require("html-css"):setup();

**Comment by Jezda1337** [comment]
How many html files you have in your root folder?

**Comment by wouterschiedam** [comment]
In the root 0, but I have a lot in sub folders

**Comment by Jezda1337** [comment]
Ye, the moment when you open neovim in root folder, plugin start scanning for all html files in root or in sub folders, then start parsing each file, so I believe that you have too much html files, and the plugin can't parse them all at once. This is issue with the plugin, if you check in some other project where you have less html files its gonna work. I'm currently soo busy with the work, but I will give my best to find time and work on the plugin.

**Comment by wouterschiedam** [comment]
Hmmm that makes sense. No worries.
I've created a new folder with a ./git folder and an index.html file but it still doesn't work :(

**Comment by Jezda1337** [comment]
Strange, do you have your neovim config somewhere on the internet, so I can take a look and investigate more? what CmpStatus said now?

**Comment by wouterschiedam** [comment]
This is what my CmpStatus says:

# ready source names
- buffer
- path
- luasnip

# unused source names
- cmdline
- nvim_lua
- html-css

# unknown source names
- nvim_lsp

**Comment by Jezda1337** [comment]
Can you make a package.json file inside the root folder and try again?

**Comment by wouterschiedam** [comment]
Still not working im, gonna publish my nvim setup maybe u can see what I'm doing wrong

**Comment by Jezda1337** [comment]
That would be the best

**Comment by wouterschiedam** [comment]
https://github.com/wouterschiedam/nvim-vetup

**Comment by wouterschiedam** [comment]
Yess it works now! thanks for helping out! still a bit curious how did u debug this problem?

**Comment by Jezda1337** [comment]
Reading the code and trying couple of times, I was 100% that the plugin is loaded but the it being ignored for some reason, then I load developer version and put some logs but nothing happened, then I notice lsp-zero v1 and I know there was huge upgrade v3. V1 for some reason was blocking external plugins like nvim-html-css so I just end up upgrading the plugin and works, I try as well to add my plugin as dependencies to lsp-zero that din't work in v1, didn't try for v3.
