### ISSUE TITLE
Doesnt work in LazyVim

### ISSUE THREAD

**Issue by muneebusmani** [Jezda1337/nvim-html-css#15]
i just did everything according to the instructions and then nvim crashes instantly after opening in terminal, but if i open it inside tmux ,then it gets stuck then after 10 seconds this whole error pops up :
Error executing luv callback:
Failed to run `config` for nvim-html-css

...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: .../.local/share/nvim/lazy/plenary.nvim/lua/plenary/jo
b.lua:499: 'fd -a -e css --exclude node_modules' was unable to complete in 5000 ms

# stacktrace:
  - /plenary.nvim/lua/plenary/async/async.lua:18 _in_ **callback_or_next**
  - /plenary.nvim/lua/plenary/async/async.lua:45 _in_ **step**
  - /plenary.nvim/lua/plenary/async/async.lua:48 _in_ **execute**
  - /plenary.nvim/lua/plenary/async/async.lua:108 _in_ **run**
  - .config/nvim/lua/plugins/completion.lua:93 _in_ **config**
  - .config/nvim/lua/config/lazy.lua:10
  - .config/nvim/init.lua:2
  
Press ENTER or type command to continue

/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:99: /home/muneeb/.config/nvim/queries/css/injections.scm: No such file or directory
stack traceback:
        [C]: in function 'error'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:99: in function 'get_files'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:215: in function 'get'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:114: in function 'get_string_parser'
        ...al/share/nvim/lazy/nvim-html-css/lua/html-css/remote.lua:53: in function 'cb'
        ...al/share/nvim/lazy/nvim-html-css/lua/html-css/remote.lua:26: in function '_user_on_exit'
        .../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:240: in function '_shutdown'
        .../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:47: in function <.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:38>
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        ...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:481: in function <...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:480>
        [C]: in function 'xpcall'
        .../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:113: in function 'try'
        ...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:480: in function 'source'
        ...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:439: in function 'source_runtime'
        ...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:407: in function 'packadd'
        ...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:131: in function 'startup'
        ...uneeb/.local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:110: in function 'setup'
        /home/muneeb/.config/nvim/lua/config/lazy.lua:10: in main chunk
        [C]: in function 'require'
        /home/muneeb/.config/nvim/init.lua:2: in main chunk
Press ENTER or type command to continue

i have treesitter parser set up for css and this plugin worked for the first time but after closing and reopening nvim, this doesnt work no matter how hard i try

**Comment by Jezda1337** [comment]
Can you share your configuration with me? It appears that there is an issue with the parser.2
Do you have [this](https://github.com/sharkdp/fd) installed?

**Comment by muneebusmani** [comment]
i have rg and fd  both installed when i first installed LazyVim , my configuration is [here](https://github.com/muneebusmani/Nvim), i didnt remove your plugin just made it lazy load so i can at least use my configuration until this issue gets fixed, if i dont put lazy=true in this, then neovim will exit instantly when opened

**Comment by Jezda1337** [comment]
Okay, I will take a look and update here

**Comment by muneebusmani** [comment]
update: sorry man for disturbing your peace, this was a parser's issue, i updated something when this plugin broke and now it is working after i updated something, either it was conform.nvim or treesitter, which causes issue
