### ISSUE TITLE
[This plugin is amazing]

### ISSUE THREAD

**Issue by gipo355** [Jezda1337/nvim-html-css#18]
Seriously this is amazing, no idea why it didn't get the attention it deserves.

Really wishing it could be kept alive and get polished! Its usefulness is quite impressive.

May I suggest a repost in r/neovim? i believe some good maintainers would be happy joining this seeing things like folke contributing to cmp to help fix tailwind lsp huge lag. It possibly wasn't noticed.

One of my major concerns in neovim was the lack of something like css intellisense.

Thanks for your work

**Comment by Jezda1337** [comment]
Thank you for the kind words @gipo355. I've been posting on r/neovim and others seem to really appreciate it. For me, what matters most is that it gets the job done. Whether the plugin becomes popular or not is of lesser importance to me.

Soon, Neovim will implement a file change tracking system, which is crucial for this plugin. This will happen sometime in version 0.11, so I'm waiting for that before rewriting the entire plugin. If you'd like to share it with someone or on r/neovim, feel free to do so.

**Comment by gipo355** [comment]
> Thank you for the kind words @gipo355. I've been posting on r/neovim and others seem to really appreciate it. For me, what matters most is that it gets the job done. Whether the plugin becomes popular or not is of lesser importance to me.
> 
> Soon, Neovim will implement a file change tracking system, which is crucial for this plugin. This will happen sometime in version 0.11, so I'm waiting for that before rewriting the entire plugin. If you'd like to share it with someone or on r/neovim, feel free to do so.

So happy to hear that!

closing as it's not a real an issue
