### ISSUE TITLE
Lazy.nvim giving error: Failed to run `config` for nvim-html-css

### ISSUE THREAD

**Issue by farzadmf** [Jezda1337/nvim-html-css#21]
Hi, I recently added this plugin, however I'm getting the following error:
```
Failed to run `config` for nvim-html-css

.../data/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...r/neovim/0.9.5/share/nvim/runtime/lua/vim/treesitter.lua:147: str: expected string, got nil

# stacktrace:
  - /plenary.nvim/lua/plenary/async/async.lua:18 _in_ **callback_or_next**
  - /plenary.nvim/lua/plenary/async/async.lua:45 _in_ **step**
  - /plenary.nvim/lua/plenary/async/async.lua:48 _in_ **execute**
  - /plenary.nvim/lua/plenary/async/async.lua:108 _in_ **run**
  - ~/.config/nvim/lua/plugins/coding/deps/nvim-cmp/nvim-html-css.lua:15 _in_ **config**
  - /cmp-buffer/after/plugin/cmp_buffer.lua:1
  - vim/_editor.lua:0 _in_ **cmd**
```

This is my config:
```lua
{
  url = 'https://github.com/Jezda1337/nvim-html-css',
  name = 'nvim-html-css',
  config = function()
    --
    require('html-css'):setup()
  end,
}
```

As you might have guessed, I'm loading this plugin as a dependency for `nvim-cmp`, and the weird thing is that I'm getting this error in a non-css file (probably once `nvim-cmp` tries to load this guy)

**Comment by Jezda1337** [comment]
Hi, can you try to add dependencies like this: 
```lua
dependencies = {
  "nvim-treesitter/nvim-treesitter",
  "nvim-lua/plenary.nvim"
},
```
In case you get some new error, pls post an error message or ss of the error.

**Comment by farzadmf** [comment]
Thank you @Jezda1337 for the reply. I added the dependencies and it seems like I'm not getting the error anymore (still too soon to say honestly because I was getting it randomly I think).

But now it seems that it adds a HUGE delay to `nvim-cmp`; basically, I do `nvim-cmp` in Lazy on `event = 'InsertEnter'`, and when I enable `nvim-html-css` and want to go to insert mode, I see about 2-3 seconds delay until the cursor becomes responsive.

Is that expected behavior? Did I miss configuring something properly?

**Comment by Jezda1337** [comment]
That is expected behavior. This is happening for 2 reasons: 1. because we are using tree-sitter to parse and extract class/ids names from a file, and 2. because there is a huge file to download + parse. I'm sorry for bad performance, I plan to work on this soon

**Comment by farzadmf** [comment]
> That should fix the problem

You mean the delay problem? Reading your comment, it seems like the delay problem is expected to be there? 🤔

Is it possible to do something about the delay? Because, honestly, it's very annoying and I had to disable this plugin.

I think some plugins use Lazy's `build` command to do some "initial" stuff; so maybe that's a good candidate to do the heavy work only the first time plugin is installed (or updated).

**Comment by Jezda1337** [comment]
As far as I understand, your issue with delay occurs when you start typing, and this should be solvable by following the comment above.

The plugin operates by scanning all the files specified in the settings. For instance, if you've kept the default settings, the plugin will scan all HTML, CSS, LESS, and SASS files, and if you have CDN links, this might introduce a slight delay of 1-2 seconds. The reason behind this delay is that all these files need to be parsed in order to extract the necessary data, including CDN files. However, this only occurs if you have exceptionally large files. Personally, I use the plugin with a large number of SCSS files and haven't encountered this issue.

**Comment by farzadmf** [comment]
> this should be solvable by following the comment above.

Ah, so you mean the delay should be solved if you use it as a stand-alone plugin?

And question: since I'm lazy-loading all my plugins (using `lazy.nvim`), what could be a good candidate for loading this plugin? Based on a file type? Based on an event?

**Comment by Jezda1337** [comment]
The plugin heavily depends on `tree-sitter`. And the best thing you can do is use the same lazy events on `tree-sitter` and `nvim-html-css`.

Delay while typing should be solved by making the plugin standalone (it should not be inside any other plugin as a dependency).
If you have 100 CSS files and each file has more than 1000 lines, then the plugin will still cause some delays, but only at the start of neovim.

**Comment by Jezda1337** [comment]
I would appreciate your feedback if you tried the suggestion from above.

**Comment by chungbae** [comment]
Hey Jezda, 

Thank you for the great plugin!  I am a new nvim user, using lazyvim distro, trying to transition from VScode and this CSS intelli-sense was one of the plugin that i was desperately looking for. 

I spent quite some time trying to make existing nvim-cmp(html-lsp autocomplete) capability to work along side your plugin and i have finally got it to work(still working on getting your pretty formatting to work).

anyways, here are the steps that i've taken to get it working. 

1. Create 'nvim-html-css.lua' file inside plugins dir.  
2. paste below into above file.
![image](https://github.com/Jezda1337/nvim-html-css/assets/43596302/86410ad0-1958-455e-a489-f178d1b83990)

Success and Enjoy!

**Comment by Jezda1337** [comment]
@chungbae 
I'm happy to hear that the plugin is helping you write code every day. If you encounter any problems with the "pretty formatting" feature, please let me know. I'll be more than happy to assist you.

**Comment by sangramsingha** [comment]
> Hey Jezda,
> 
> Thank you for the great plugin! I am a new nvim user, using lazyvim distro, trying to transition from VScode and this CSS intelli-sense was one of the plugin that i was desperately looking for.
> 
> I spent quite some time trying to make existing nvim-cmp(html-lsp autocomplete) capability to work along side your plugin and i have finally got it to work(still working on getting your pretty formatting to work).
> 
> anyways, here are the steps that i've taken to get it working.
> 
>     1. Create 'nvim-html-css.lua' file inside plugins dir.
> 
>     2. paste below into above file.
>        ![image](https://private-user-images.githubusercontent.com/43596302/318641596-86410ad0-1958-455e-a489-f178d1b83990.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MjE1ODAsIm5iZiI6MTcxMjcyMTI4MCwicGF0aCI6Ii80MzU5NjMwMi8zMTg2NDE1OTYtODY0MTBhZDAtMTk1OC00NTVlLWE0ODktZjE3OGQxYjgzOTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAzNTQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmYzMzZmM2MmJmOTA2OWFhMzFlZDI3ZDgwZTE3MGYwNDIyMzdhMjFmODhmNDM0YjUxOGZlYWI3ZjI0OTRkNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3YcOH0Wnnhp9alUW0SYT0DoAQV3CfNK6MWxTc7asz84)
> 
> 
> Success and Enjoy!

well this worked for me thanks
