### ISSUE TITLE
Not working with template literals

### ISSUE THREAD

**Issue by Gogiu23** [Jezda1337/nvim-html-css#24]
It works great with React but when i use template literals doesn't work the sources for the completion:
Example:
This case doesn't work
`className={`${style.ofcanvas} d-flex flex-column bg-secondary`}`
This one works great
`className="d-flex flex-column bg-secondary";`
Great works anyway.
The plugin is amazing.

**Comment by Jezda1337** [comment]
@Gogiu23 I have added the ability for autocomplete in jsx-expressions. For example, className={`${value} other classes`}(use backticks). If you try it, please close this issue. Thank you.

**Comment by Gogiu23** [comment]
Great. It works!!!
