### ISSUE TITLE
Enhanced HTML-CSS Autocompletion Features for Neovim

### ISSUE THREAD

**Issue by ESSO0428** [Jezda1337/nvim-html-css#25]
Hello everyone,

I have been working on a fork of the HTML-CSS autocompletion plugin for Neovim, and I'm excited to share some enhancements that might be beneficial for the community. My fork can be found here: https://github.com/ESSO0428/nvim-html-css.

![img](https://private-user-images.githubusercontent.com/92996726/321911120-4b0d161b-0c72-4751-9b5a-446d271feeb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MzY3ODEsIm5iZiI6MTcxMjkzNjQ4MSwicGF0aCI6Ii85Mjk5NjcyNi8zMjE5MTExMjAtNGIwZDE2MWItMGM3Mi00NzUxLTliNWEtNDQ2ZDI3MWZlZWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDE1NDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MzUyZTBhYWQ5ZDJmZTMyOTJjNTQ2Mzg5NDFkNmM0NzMzNDc3NzljNzFlZjBmYjljODc4NTljYjI2ZDBmYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._2rwdNryYXIR9t4ghFqiPIbqCmLkhog31-qi4xsmO3o)

## Enhancements include:

- **External Git Repository Support:** The plugin now operates smoothly outside of a git repository, maintaining a performance that is robust and efficient.It supports autocompletion for both CSS `classes` and `ids`, enhancing coding efficiency.
- **Selective File Reading:** Instead of loading the entire working directory, the plugin now only reads the style tags and linked CSS from the currently open HTML file. This significantly reduces performance overhead.
- **Asynchronous Operations and CSS File Monitoring:** Implemented mechanisms for asynchronous operations and monitoring changes in CSS files to improve responsiveness and reduce lag.
- **Caching for Remote URLs:** To enhance performance, the plugin now downloads and caches files from remote URLs, speeding up subsequent accesses to these files.
- **Enhanced Template Support for htmldjango:** In addition to the above, for `htmldjango` files (*.html), the plugin will also read templates extended by the current file, including any href or style tags within those templates.
- **Completion Item Symbols:** 
    - Items from the `style tags` in the **current HTML file** are marked with a star symbol (★) to indicate their source.
    - Items from **remote CSS files** linked (`link tags`) via href in previously accessed HTML files are marked with a globe symbol (🌐) to denote their remote origin.
    - Completion items from **local CSS files** linked (`link tags`) via href in any HTML file do not have a symbol, maintaining a clean and simple identification.

I hope these enhancements will be helpful for your ongoing development and perhaps could be integrated into the original project. I'm looking forward to any feedback or suggestions you might have!

Best regards,

Thank you to the development team for your hard work and dedication.

**Comment by Jezda1337** [comment]
Thank you for sharing these amazing enhancements. They will be very helpful for the upcoming development of the plugin. I have a bunch of ideas to improve the user experience and plugin performance, and these enhancements will definitely be beneficial in implementing those ideas. Once again, thank you for sharing!
