### ISSUE TITLE
Follow the guide, got Failed to run `config` for nvim-html-css

### ISSUE THREAD

**Issue by JiuRanYa** [Jezda1337/nvim-html-css#26]
Hi, I'm so happy to use this awesome plugin, but when i follow the guide, plugin not work and i got this error. Could you pls help me ?
```
Failed to run `config` for nvim-html-css

.../data/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...r/neovim/0.9.5/share/nvim/runtime/lua/vim/treesitter.lua:147: str: expected string, got nil

# stacktrace:
  - /plenary.nvim/lua/plenary/async/async.lua:18 _in_ **callback_or_next**
  - /plenary.nvim/lua/plenary/async/async.lua:45 _in_ **step**
  - /plenary.nvim/lua/plenary/async/async.lua:48 _in_ **execute**
  - /plenary.nvim/lua/plenary/async/async.lua:108 _in_ **run**
  - ~/.config/nvim/lua/plugins/coding/deps/nvim-cmp/nvim-html-css.lua:15 _in_ **config**
  - /cmp-buffer/after/plugin/cmp_buffer.lua:1
  - vim/_editor.lua:0 _in_ **cmd**
```

here is my nvim config https://github.com/JiuRanYa/dev-dot-file/tree/main/.config/nvim/lua

By the way, I'm using [Nvchad](https://nvchad.com/)

**Comment by JiuRanYa** [comment]
I searched past issues and it seems that none of the methods mentioned work.

**Comment by Jezda1337** [comment]
Hey @JiuRanYa, thanks for sharing your config. I will take a look and come back with a solution.

**Comment by JiuRanYa** [comment]
So thanks!

**Comment by Jezda1337** [comment]
Hey @JiuRanYa, the issue is in the cmp configuration, it seems that to work you need to change from opts to config. 
Once you test it pls close the issue.

https://github.com/Jezda1337/nvim-html-css/assets/42359294/e2833f53-0ad1-4582-89f6-4ab50d4129c1

**Comment by JiuRanYa** [comment]
@Jezda1337 Your help is greatly appreciated, maybe nvchad overrides opts, thanks again！！
