### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pabloeltdev** [Jezda1337/nvim-html-css#28]
I could not get it to work, no error messages are displayed and the source is listed under unused source names in CmpStatus.

Versions:
- Neovim: 0.10.1 (LuaJIT 2.1.1725453128)
- fd: 10.2.0

Details:
[x] - Tested inside a git repository.

My config: https://github.com/pabloeltdev/.workenv/tree/main/neovim/.config/nvim

**Comment by Jezda1337** [comment]
Do you have a package.json or .git folder in ur root?

**Comment by pabloeltdev** [comment]
I have a .git folder

**Comment by pabloeltdev** [comment]
I reviewed my config today and the `sources` settings were probably being overwritten.
