### ISSUE TITLE
Unable to connect to the URL localhost:8000/gradient-tests.html

### ISSUE THREAD

**Issue by adonespitogo** [Jezda1337/nvim-html-css#29]
I'm getting this error after updating my lazy plugins:

![Screenshot From 2024-11-01 23-14-27](https://github.com/user-attachments/assets/8edb82c9-e904-4901-b9c7-bfc3fa44230c)

nvim-html-css.lua:
```lua
return {
    "Jezda1337/nvim-html-css",
    dependencies = {
        "nvim-treesitter/nvim-treesitter",
        "nvim-lua/plenary.nvim",
        "sharkdp/fd",
    },
    config = function()
        require("html-css"):setup({})
    end,
}
```

nvim-cmp.lua:
```lua
{
    name = "html-css",
    option = {
        enable_on = { "html", "vue", "ejs", "pug", "eruby", "haml" },
        file_extensions = { "css", "sass", "less" }, -- set the local filetypes from which you want to derive classes
        style_sheets = {
            -- example of remote styles, only css no js for now
            -- "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css",
        },
    },
},
```

**Comment by Jezda1337** [comment]
Can you share `gradient-tests.html`?

**Comment by adonespitogo** [comment]
I don't know where to find this file. I don't know why html-css is calling such file as well.

**Comment by Jezda1337** [comment]
Perhaps, somewhere in ur root dir is the html  file with `<link rel="stylesheet" href="http://localhost:8000/gradient-tests.html" />`
The plugin will look for .git or package.json in current dir and one level up dir, and one level down, so do you have this line of code somewhere in the current dir or one level up or one level down?

**Comment by Jezda1337** [comment]
Bdw, if you want you can edit this by ur self, in `./local/share/nvim/lazy` you should be able to find `html-css` plugin, and just add this `args = { "-a", "-e", "html", "--exclude", "node_modules", "--exclude", "sdk" },`
here: https://github.com/Jezda1337/nvim-html-css/blob/c514bd27ad560636ed39dea3e370b3103754e244/lua/html-css/hrefs.lua#L18

this would be quick fix for you.

**Comment by adonespitogo** [comment]
Thanks, I will just fork your repo for now and apply this change. Do you know when html-css v2 will be available? And what version of neovim will it work?

**Comment by Jezda1337** [comment]
Currently only work for nightly version of neovim, but once I finish all the staff it will work on stable as well. I hope it will be ready soon, if you are on nightly version you can try it.

For v1 and this issue I will create an option in config so ppl can add directories which will be excluded.

**Comment by Jezda1337** [comment]
I have added new config to exclude directories from scanning. You can take a look. Cheers
https://github.com/Jezda1337/nvim-html-css/tree/main?tab=readme-ov-file#-configuration
