### ISSUE TITLE
not work on laravel blade

### ISSUE THREAD

**Issue by maybeenang** [Jezda1337/nvim-html-css#31]
## Description
plugin does not work correctly with Laravel Blade files, while functioning normally in standard HTML files. 

### Environment
- **Neovim Version**: 0.10.2

### Treesitter Configuration
Installed Treesitter parsers:
- blade
- html
- css
- php_only
- php

### Steps to Reproduce
1. Open a Laravel Blade file (`.blade.php`)
2. Attempt to use plugin features (autocomplete)
3. Observe that plugin functionality is broken or incomplete

### Current Configuration

```lua
	{
		"Jezda1337/nvim-html-css",
		name = "html-css",
		dependencies = {
			"nvim-treesitter/nvim-treesitter",
			"nvim-lua/plenary.nvim",
		},
		lazy = false,
		after = "nvim-cmp",
		event = { "BufRead", "BufNewFile" },
		config = function()
			require("html-css"):setup()
		end,
	}
```

```lua
{
	name = "html-css",
	option = {
		enable_on = {
			"blade",
			"html",
			"php",
		}, -- set the file types you want the plugin to work on
		dir_to_exclude = { "node_modules" },
		file_extensions = { "css", "sass", "less" }, -- set the local filetypes from which you want to derive classes
		style_sheets = {
			-- example of remote styles, only css no js for now
			"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css",
			"https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css",
		},
	},
},
```

**Comment by Jezda1337** [comment]
No error messages?

**Comment by maybeenang** [comment]
> No error messages?

yes there is no error message, just when i type CmpStatus in blade file, just showing # unavailable source names
but when i run CmpStatus on regular html file html-css is showing on # ready sources name

**Comment by Jezda1337** [comment]
Hey @maybeenang , I have pushed the fix. Once you try it pls close this issue.

**Comment by maybeenang** [comment]
> Hey @maybeenang , I have pushed the fix. Once you try it pls close this issue.

thank you so much
