### ISSUE TITLE
Can autocompletion be updated dynamically?

### ISSUE THREAD

**Issue by dddddjent** [Jezda1337/nvim-html-css#6]
![image](https://github.com/Jezda1337/nvim-html-css/assets/100690267/504da071-8172-407a-b277-73392dbd8fd3)
When I commented all the style sheet sources in the nvim-cmp config
![image](https://github.com/Jezda1337/nvim-html-css/assets/100690267/4ccb815a-2675-4a04-ab29-52365146b1ca)
After I uncommented the link in html source file, I couldn't get the completion instantly
![image](https://github.com/Jezda1337/nvim-html-css/assets/100690267/0cb8fbb6-ad16-41a8-a6e2-82cf138fb2af)
When I re-entered the nvim, it appeared.
Also, if I add it to the source of cmp, my completion items will be doubled. Is this how it supposed to be?
Btw, css files seem to be updated correctly.

**Comment by Jezda1337** [comment]
That is a bug, the plugin needs improvements, I am busy  last couple of weeks, but I will start improving plugin asap.

**Comment by Jezda1337** [comment]
Actually this is not a bug, it is not possible to change the editor settings and see the results without opening the editor again. As for the html and css files, it is possible because they are not part of the editor and its settings.
